# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: ai-chat-quickstart-csharp
metadata:
  template: ai-chat-quickstart-csharp@0.1.0-beta
requiredVersions:
    azd: ">= 1.10.0"
services:
  aca:
    project: src/AIChatApp/
    language: csharp
    host: containerapp
    docker:
      remoteBuild: true
pipeline:
  variables:
    - AZURE_OPENAI_DEPLOYMENT
    - AZURE_OPENAI_MODEL
    - AZURE_OPENAI_RESOURCE_LOCATION
hooks:
  # Create .NET User Secrets for all generated environment variables
  postprovision:
    windows:
      shell: pwsh
      run: ./infra/post-script/store-env-vars.ps1
      interactive: false
      continueOnError: true
    posix:
      shell: sh
      run: ./infra/post-script/store-env-vars.sh
      interactive: false
      continueOnError: true
